## modify this
# TODO requirements

---
- hosts: localhost
  remote_user: root
  become_user: root
  become_method: sudo
  become: yes

  roles:
    - geerlingguy.mysql
    - ergonlogic.drush
    - ansible-role-aegir
  vars:
    # Use default log file size so Travis CI VM allows MySQL restart.
    - aegir_frontend_url: aegir-xenial-php7.local
    - mysql_innodb_log_file_size: "5M"
    - aegir_dependencies:
      - apache2
      - mysql-client
      - php
      - php-cli
      - php-gd
      - php-mysql
      - postfix
      - sudo
      - rsync
      - git
      - unzip
      - libapache2-mod-php7.0
      - htop
      - curl
      - wget
    - aegir_install_additional_packages: true
    - aegir_additional_packages:
      - php-curl